### ISSUE TITLE
How to get/modify roles on a server?

### ISSUE THREAD

**Issue by AtmoEntity** [NotGGhost/jDiscord#24]
I don't see any way to get a list of roles on a server, or modify them. Does this functionality exist?

**Comment by NotGGhost** [comment]
It's in the next update.

**Comment by AtmoEntity** [comment]
Awesome, I appreciate it! Great work you're doing here.

**Comment by NotGGhost** [comment]
Working on it now.

**Comment by mcNETDev** [comment]
from the GroupUser class the method getRoles() is return null is this right?

**Comment by NotGGhost** [comment]
No. Ensure you are on 2.1.2
