### ISSUE TITLE
Sending a YouTube link

### ISSUE THREAD

**Issue by stelar7** [NotGGhost/jDiscord#25]
Sending a YouTube link provides the following error:

DiscordAPI: Failed to process message:
 {"id":"132284006938050560","embeds":[{"thumbnail":"width":480,"proxy_url":"xxx","url":"xxx","height":360},"provider":{"name":"YouTube","url":"www.youtube.com/"},"author":{"name":"xxx","url":"xxx"},"description":null,"video":{"width":480,"url":"xxx","height":270},"type":"video","title":"xxx","url":"xxx"}],"channel_id":"xxx"}

Add a Object for Videos or something?

**Comment by NotGGhost** [comment]
http://itsghost.me/jdiscord.jar; beta build from a while ago
Try that

**Comment by stelar7** [comment]
That seems to work, but now it prints "sendMessage"s to the console :/

Also, why the change from build(); to build(api); ?

Using a Jar is really inconvenient for me, so could you update the Maven repo?

**Comment by NotGGhost** [comment]
Maven support has been added... 
me.itsghost
jDiscord
2.0
