### ISSUE TITLE
Got a deprecated error: 

### ISSUE THREAD

**Issue by MrMadPanda** [NotGGhost/jDiscord#28]
So I got a deprecated error that asked to be reported if found soo... here:
This is all the code I wrote:

    import me.itsghost.jdiscord.DiscordAPI;
    import me.itsghost.jdiscord.DiscordBuilder;
    import me.itsghost.jdiscord.exception.BadUsernamePasswordException;
    import me.itsghost.jdiscord.exception.DiscordFailedToConnectException;
    import me.itsghost.jdiscord.exception.NoLoginDetailsException;
    public class Main {

	public static void main(String[] args) {
                // clearly I put an actual email and password in here
		DiscordAPI api = new DiscordBuilder("MYEMAIL", "MYPASSWORD").build();
		try {
			api.login();
		} catch (NoLoginDetailsException e) {
			e.printStackTrace();
		} catch (BadUsernamePasswordException e) {
			e.printStackTrace();
		} catch (DiscordFailedToConnectException e) {
			e.printStackTrace();
		}
		
		while(!api.isLoaded()){
			try {
				Thread.sleep(500);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

	
		api.stop();
		
	 }
    }

And got this in my console: 
DiscordAPI: Attempting to login!
DiscordAPI: Logged in and starting session!
DiscordAPI: Token: //deleted this
DiscordAPI: Logged in and loaded!
DiscordAPI: Successfully loaded user data!
DiscordAPI: Shutting down!
DiscordAPI: Your data is on a different server
DiscordAPI: This error is deprecated... if you're seening this, report it.

Same thing happens if I get rid of the Thread.sleep stuff

**Comment by NotGGhost** [comment]
Fixed in 2.0... sorry about that
