### ISSUE TITLE
Internal Client Error

### ISSUE THREAD

**Issue by cjlim2007** [NotGGhost/jDiscord#36]
I'm not sure where this problem comes from but my code was working 2 days ago and now it doesn't.  I did not change anything within those days but now when I try to run the code I get something like this in the console:

DiscordAPI: Attempting to login!
DiscordAPI: Logged in and starting session!
DiscordAPI: Token: some token
Internal client error!
DiscordAPI: Attempting go log in (again?)!
DiscordAPI: Shutting down!

Then it just repeats until I stop the program.  There are no errors in the code and it was running the same exact code only a few days ago.  Is this a fixable problem?

**Comment by TheWithz** [comment]
There are many people on the forum and even some who are not experiencing this problem.

**Comment by Almighty-Alpaca** [comment]
@cjlim2007 you should probably hide your token

**Comment by cjlim2007** [comment]
By the way the problem was fixed when I got the nv-websocket-client but I dont know how to use maven so I'm not sure if I'm running into other problems because I haven't used maven.
