### ISSUE TITLE
Not Sure How To Install Project

### ISSUE THREAD

**Issue by kuroodo** [NotGGhost/jDiscord#41]
I'm not really all that experienced with adding projects, plugins and such things in eclipse.

I was using jDiscord 2.0 or below I believe (the version released at the very beginning of Januray) . All I did was create a java project, add the jdiscord.jar as a library and that's it. I was able to make myself a small test bot for my discord server. Now it won't log in anymore.

So I added the latest version (2.1.2) as a library, but I'm getting a NoClassDefFoundError exception when I tried to run the program (this is the error https://github.com/NotGGhost/jDiscord/issues/39 ). I then read that I needed maven, so this must be the reason. I've installed maven but I just don't know what to do from here. The different ways I tried to import the project lead to errors in the class files.

**Comment by TheWithz** [comment]
have you editted your pom.xml file?

**Comment by kuroodo** [comment]
Nope. I made a new clean workspace and tried using the pom file in the jDiscord-master zip file. This loads up the source code/project, but full of errors as mentioned before.

The main issue is that I have no idea what I'm doing with maven. I don't know how to implement it onto one of my projects, nor how to import a maven project. I've done some googling but I can't get anything to work.

**Comment by TheWithz** [comment]
You are missing the neovissionaries websocket plugin I believe

**Comment by kuroodo** [comment]
Okay so after playing around further, and adding the eovissionaries websocket dependency, I managed to get somewhere. I am now receiving the same error being reported here https://github.com/NotGGhost/jDiscord/issues/40

Will do some more digging. Not sure if I should close this yet

**Comment by BrutalCSkakan** [comment]
Tell me if you find the solution @kuroodo
